---
- hosts: all
  become: true
  tasks:
    - name: update repository index
      apt:
        update_cache: yes

    - name: install apache engine
      apt:
        name: apache2
        state: latest

    - name: install apache 2 php
      apt:
        name: libapache2-mod-php
        state: latest
